import dayjs from 'dayjs/esm';
import { IEnquiryDetails } from 'app/entities/enquiry-details/enquiry-details.model';
import { IBranch } from 'app/entities/branch/branch.model';
import { ISecurityUser } from 'app/entities/security-user/security-user.model';
import { Title } from 'app/entities/enumerations/title.model';
import { Gender } from 'app/entities/enumerations/gender.model';
import { ResidentalStatus } from 'app/entities/enumerations/residental-status.model';
import { MaritalStatus } from 'app/entities/enumerations/marital-status.model';
import { Occupation } from 'app/entities/enumerations/occupation.model';
import { Status } from 'app/entities/enumerations/status.model';
import { LoanStatus } from 'app/entities/enumerations/loan-status.model';
import { StepperNumber } from 'app/entities/enumerations/stepper-number.model';

export interface IMember {
  id: number;
  title?: Title | null;
  firstName?: string | null;
  middleName?: string | null;
  lastName?: string | null;
  memberId?: string | null;
  membershipNo?: string | null;
  fatherName?: string | null;
  motherName?: string | null;
  gender?: Gender | null;
  dob?: dayjs.Dayjs | null;
  email?: string | null;
  mobileNo?: string | null;
  alternateMobile?: string | null;
  fax?: string | null;
  contactTimeFrom?: string | null;
  contactTimeTo?: string | null;
  religion?: string | null;
  custCategory?: string | null;
  cast?: string | null;
  aadharCardNo?: string | null;
  panCard?: string | null;
  passportNo?: string | null;
  passportExpiry?: string | null;
  rationCard?: string | null;
  residenceStatus?: ResidentalStatus | null;
  maritalStatus?: MaritalStatus | null;
  familyMemberCount?: number | null;
  occupation?: Occupation | null;
  nationality?: string | null;
  noOfDependents?: number | null;
  applicationDate?: dayjs.Dayjs | null;
  status?: Status | null;
  highestQualification?: string | null;
  hasAdharCardVerified?: boolean | null;
  hasPanCardVerified?: boolean | null;
  loanStatus?: LoanStatus | null;
  enqRefrenceNo?: string | null;
  numberOfAssets?: number | null;
  isActive?: boolean | null;
  isDeleted?: boolean | null;
  profileStepper?: StepperNumber | null;
  lastModified?: dayjs.Dayjs | null;
  lastModifiedBy?: string | null;
  createdBy?: string | null;
  createdOn?: dayjs.Dayjs | null;
  freeField1?: string | null;
  freeField2?: string | null;
  freeField3?: string | null;
  freeField4?: string | null;
  freeField5?: string | null;
  freeField6?: string | null;
  enquiryDetails?: Pick<IEnquiryDetails, 'id'> | null;
  branch?: Pick<IBranch, 'id'> | null;
  member?: Pick<IMember, 'id'> | null;
  securityUser?: Pick<ISecurityUser, 'id'> | null;
}

export type NewMember = Omit<IMember, 'id'> & { id: null };
